analytics.onpremise.enable=false
analytics.integration.enable=true
analytics.project="{\\n  \\"id\\"\: 3342160,\\n  \\"name\\"\: \\"MM-PROJECT\\",\\n  \\"teamId\\"\: 3314179,\\n  \\"organizationId\\"\: 812758,\\n  \\"isSampleProject\\"\: false,\\n  \\"canAutoIntegrate\\"\: false\\n}"
analytics.team="{\\n  \\"id\\"\: 3314179\\n}"
analytics.testcloud.integration.enable=false
analytics.testreport.autoupload.enable=true
analytics.testcloud.hub.switchHub.enable=false
