<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PWD</name>
   <tag></tag>
   <elementGuidId>de921807-02ab-41ea-a6a0-f5b65940c3b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b46fdd33-ae1a-4162-a14b-7a57d2d2389f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password *</value>
      <webElementGuid>041a570e-06b2-4e91-af27-db39adb7cd1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input undefined</value>
      <webElementGuid>d50c70bc-302d-4eba-a844-0d6bcd3e1245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>109ac59e-3e82-4e6b-8377-45b105cd9491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>1a6e732c-3b9f-4523-8ad4-58423d259e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/section[@class=&quot;sectionTwo styles_loginBox__DYG_V&quot;]/div[@class=&quot;wraper&quot;]/div[@class=&quot;styles_mainSec__IDj2h&quot;]/form[@class=&quot;styles_form__qmKve&quot;]/div[@class=&quot;form-group styles_formGroup__1kaxM&quot;]/div[@class=&quot;form-sec undefined undefined&quot;]/input[@class=&quot;input undefined&quot;]</value>
      <webElementGuid>2c6c1b93-661f-4745-991c-4a31f9d276f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>560bc3fc-464e-49ba-9a13-125f732fa0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>da287234-ccce-4641-b946-be38450767e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Password *' and @type = 'password' and @name = 'password']</value>
      <webElementGuid>f0dd7061-85e0-4efd-a230-e6f7e4540ac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
